---
title: "Returns Distribution"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    vertical_layout: fill
---

```{r setup, message = FALSE,include = FALSE}
library(tidyverse)
library(tidyquant)
library(scales)
library(highcharter)
library(tidyquant)
library(timetk)
library(shiny)
library(PerformanceAnalytics)
library(shinydashboard)
library(flexdashboard)
library(broom)
library(tibbletime)
library(readr)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
 
temp = tempfile()

download.file(
  "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Global_3_Factors_CSV.zip",
  temp
)

Global_3_Factors = read_csv(unz(temp,"Global_3_Factors.csv"),skip = 6) %>%
  rename(date = X1) %>% mutate_at(vars(-date),as.numeric) %>% mutate(date = ymd(parse_date_time(date,"%Y%m")))


```

Sidebar {.sidebar}
===================================

```{r}
fluidRow(
  column(6,
         textInput("stock1","Stock 1","SPY")),
  column(5,
         numericInput("w1","Portf. %",20,min = 1, max= 100))
)

fluidRow(
  column(6,
  textInput("stock2", "Stock 2", "EFA")),
  column(5,
  numericInput("w2", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock3", "Stock 3", "IJS")),
  column(5,
  numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock4", "Stock 4", "EEM")),
  column(5,
  numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock5", "Stock 5", "AGG")),
  column(5,
  numericInput("w5", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(7,
         dateInput("date","Starting Date","2010-01-01",format = "yyyy-mm-dd"))
)

fluidRow(
  column(7,
         selectInput("rebalance","rebalance freq",
                     c("Yearly" = "years",
                       "Monthly" = "months",
                       "Weekly" = "weeks"))
  )
)

fluidRow(
  column(5,
         numericInput("window","Window",12,min=3,max=36,step=1))
)

fluidRow(
  column(5,
         numericInput("rfr","Risk Free Rate %",1,min=0,max=10,step=1))
)

fluidRow(
  column(5,
  numericInput("sim_months", "Months", 120, min = 6, max = 240, step = 6)),
  column(5,
  numericInput("sims", "Sims", 51, min = 31, max = 101, step = 10))
)

actionButton("go","submit")

prices <- eventReactive(input$go, {
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  prices <- 
    getSymbols(symbols, src = 'yahoo', from = input$date, 
               auto.assign = TRUE, warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`(symbols)
})

w <- eventReactive(input$go, {
  w = c(input$w1/100,input$w2/100,input$w3/100, input$w4/100, input$w5/100)
})

rfr = eventReactive(input$go,{
  Rf = input$rfr/100
})

window = eventReactive(input$go,{
  window = input$window
})

portfolio_returns_byhand = eventReactive(input$go, {
  
  
  asset_returns_long = prices() %>% to.monthly(indexAt = "last",OHLC = FALSE) %>% tk_tbl(preserve_index = TRUE,
                                                                                       rename_index = "date") %>%
    gather(asset,returns,-date) %>% group_by(asset) %>% mutate(returns = (log(returns)-log(lag(returns))))
  
  portfolio_returns_byhand = asset_returns_long %>% tq_portfolio(assets_col = asset,returns_col = returns,
                                                                 weights = w(),
                                                                 col_rename = "returns")
})

portfolio_returns_xts = eventReactive(input$go,{
  prices = prices()
  w = w()
  
  prices_monthly = to.monthly(prices,indexAt = "last", OHLC = FALSE)
  asset_returns_xts = na.omit(Return.calculate(prices_monthly,method="log"))
  
  portfolio_returns_xts = Return.portfolio(asset_returns_xts,weights = w) %>% `colnames<-`("returns")
  
})


port_rolling_sd_tidy = eventReactive(input$go, {
  prices = prices()
  
  portfolio_returns_tq_rebalanced_monthly = prices %>% to.monthly(indexAt = "last",OHLC = FALSE) %>% 
    tk_tbl(preserve_index = TRUE,rename_index = "date") %>% slice(-1) %>% gather(asset,returns,-date) %>% group_by(asset) %>% mutate(returns = (log(returns) - log(lag(returns)))) %>%
      tq_portfolio(assets_col = asset,returns_col = returns,weights = w(),col_rename = "returns",rebalance_on = "months")
  
  window = input$window
  portfolio_rolling_sd_tidy = portfolio_returns_tq_rebalanced_monthly %>% tq_mutate(mutate_fun = rollapply,width = window,FUN = sd,col_rename = ("rolling_sd")) %>% select(date,rolling_sd) %>% na.omit()
})

rolling_skew_xts <- eventReactive(input$go, {
  
  rolling_skew_xts <- 
    rollapply(portfolio_returns_xts(),
            FUN = skewness,
            width = input$window) %>% 
    na.omit()

})

rolling_kurt_xts <- eventReactive(input$go, {
  rolling_kurt_xts <- 
    rollapply(portfolio_returns_xts(),
            FUN = kurtosis,
            width = input$window) %>% 
    na.omit()

})


portfolio_returns_tq_rebalanced_monthly <- eventReactive(input$go, {
  
  prices <- prices()
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  asset_returns_long <- 
      prices %>% 
      to.monthly(indexAt = "lastof", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns))))

  
  portfolio_returns_tq_rebalanced_monthly <- 
  asset_returns_long %>%
  tq_portfolio(assets_col  = asset, 
               returns_col = returns,
               weights     = w,
               col_rename  = "returns",
               rebalance_on = "months")
})

sharpe_xts = eventReactive(input$go,{
  rfr = Rf()
  SharpeRatio(portfolio_returns_xts_rebalanced_monthly,
                         Rf = rfr,
                         FUN = "StdDev") %>% `colnames<-`("sharpe_xts")
})

sharpe_tidyverse_byhand = eventReactive(input$go,{
  rfr = Rf()
  portfolio_returns_dplyr_byhand %>% summarise(sharpe_dplyr = mean(returns-rfr)/sd(returns - rfr))
})

sharpe_tq = eventReactive(input$go, {
  rfr = Rf()
  portfolio_returns_tq_rebalanced_monthly %>% tq_performance(Ra = returns,
                                                             performance_fun = SharpeRatio,
                                                             Rf = rfr,
                                                             FUN = "StdDev") %>% `colnames<-`("sharpe_tq")
})

sharpe_byhand_with_return_columns = eventReactive(input$go,{
  rfr = Rf()
  sharpe_byhand_with_return_columns = portfolio_returns_tq_rebalanced_monthly %>% mutate(ratio = mean(returns-rfr)/sd(returns-rfr)) %>% mutate(returns_below_rfr = 
                                                                                                             if_else(returns < rfr, returns, as.numeric(NA))) %>%
    mutate(returns_above_rfr = if_else(returns>rfr,returns,as.numeric(NA))) %>% mutate_if(is.numeric,funs(round(.,4)))
})

market_returns <- eventReactive(input$go, {
  
    getSymbols("SPY", src = 'yahoo', 
            from = input$date, 
             auto.assign = TRUE, 
             warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`("SPY") %>% 
    to.monthly(indexAt = "lastof", 
               OHLC = FALSE) %>% 
    Return.calculate(method = "log") %>% 
    na.omit()  
})

market_sharpe <- eventReactive(input$go, {
  
  SharpeRatio(market_returns(),
              Rf = rfr(), 
              FUN = "StdDev")
})

market_rolling_sharpe <- eventReactive(input$go, {
  
  rollapply(market_returns(), 
            window(), 
            function(x) 
            SharpeRatio(x, 
                        Rf = rfr(), 
                        FUN = "StdDev")) %>% 
  na.omit()
})

portfolio_returns <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  validate(need(input$w1 + input$w2 + input$w3 + input$w4 + input$w5 == 100, 
                "The portfolio weights must sum to 100%!"))
  
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  getSymbols(symbols, src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Ad(get(.))) %>% 
  reduce(merge) %>%
  `colnames<-`(symbols) %>% 
  to.monthly(indexAt = "lastof", 
             OHLC = FALSE) %>% 
  Return.calculate(method = "log") %>% 
  na.omit() %>% 
  Return.portfolio(weights = w)
  
})


portfolio_rolling_sharpe <- eventReactive(input$go, {

  rollapply(portfolio_returns(),
            window(),
            function(x) SharpeRatio(x, 
                                    Rf = rfr(), 
                                    FUN = "StdDev")) %>% 
  na.omit()
})

portfolio_sharpe <- eventReactive(input$go, {
  
  validate(need(input$w1 + input$w2 + input$w3 + input$w4 + input$w5 == 100, "------"))
  
  SharpeRatio(portfolio_returns(),
              Rf = rfr(), 
              FUN = "StdDev")
  
})

market_return <- eventReactive(input$go, {
  market_return <- 
    getSymbols("SPY", src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`("SPY") %>% 
    to.monthly(indexAt = "lastof", OHLC = FALSE) %>% 
    tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
    mutate(returns = (log(SPY) - log(lag(SPY)))) %>% 
    na.omit() %>%
    select(date, returns)
})

portfolio_returns_tq_rebalanced_monthly <- eventReactive(input$go, {
  
  prices <- prices()
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  portfolio_returns_tq_rebalanced_monthly <- 
      prices %>% 
      to.monthly(indexAt = "lastof", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns)))) %>% 
      na.omit() %>%
      tq_portfolio(assets_col  = asset, 
               returns_col = returns,
               weights     = w,
               col_rename  = "returns",
               rebalance_on = "months")
})

beta_dplyr_byhand <- eventReactive(input$go, {
  
  #portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  
  market_return <- market_return()
  
beta_dplyr_byhand <- 
  portfolio_returns_tq_rebalanced_monthly() %>% 
  do(model = lm(returns ~ market_return$returns, data = .))
  
})

portfolio_model_augmented <- eventReactive(input$go, {
  
  portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  
  beta_dplyr_byhand() %>% 
  augment(model) %>% 
  rename(mkt_rtns = market_return.returns) %>% 
  select(returns, mkt_rtns, .fitted) %>% 
  mutate(date = portfolio_returns_tq_rebalanced_monthly$date)
  
})



portfolio_returns_tq_rebalanced_monthly_first_day <- eventReactive(input$go, {
  
  prices <- prices()
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  portfolio_returns_tq_rebalanced_monthly_first_day <- 
      prices %>% 
      to.monthly(indexAt = "firstof", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns)))) %>% 
      na.omit() %>%
      tq_portfolio(assets_col  = asset, 
               returns_col = returns,
               weights     = w,
               col_rename  = "returns",
               rebalance_on = "months")
  
})


ff_dplyr_byhand <- eventReactive(input$go, {

  portfolio_returns_tq_rebalanced_monthly_first_day <-
    portfolio_returns_tq_rebalanced_monthly_first_day()
  
  ff_dplyr_byhand <-
  portfolio_returns_tq_rebalanced_monthly_first_day %>%
  left_join(Global_3_Factors, by = "date") %>%
  mutate(MKT_RF = `Mkt-RF`/100,
         SMB = SMB/100,
         HML = HML/100,
         RF = RF/100,
         R_excess = round(returns - RF, 4)) %>%  
  do(model = lm(R_excess ~ MKT_RF + SMB + HML, data = .)) %>% 
  tidy(model, conf.int = T, conf.level = .95) %>% 
  mutate_if(is.numeric, funs(round(., 3))) %>%
  filter(term != "(Intercept)")
})


rolling_ff_glanced <- eventReactive(input$go, {
  
rolling_lm <- rollify(.f = function(R_excess, MKT_RF, SMB, HML) {
                              lm(R_excess ~ MKT_RF + SMB + HML)
                           }, 
                      window = input$window, 
                      unlist = FALSE)
  
 
portfolio_returns_tq_rebalanced_monthly_first_day <- 
  portfolio_returns_tq_rebalanced_monthly_first_day()
  
rolling_ff_glanced <-
  portfolio_returns_tq_rebalanced_monthly_first_day %>%
  left_join(Global_3_Factors, by = "date") %>% 
  mutate(MKT_RF = `Mkt-RF`/100,
         SMB = SMB/100,
         HML = HML/100,
         RF = RF/100,
         R_excess = round(returns - RF, 4)) %>% 
  mutate(rolling_ff = rolling_lm(R_excess, MKT_RF, SMB, HML)) %>% 
  slice(-1:-(input$window -1)) %>%
  mutate(glanced = map(rolling_ff, 
                      glance)) %>% 
  unnest(glanced) %>% 
  select(date, r.squared, adj.r.squared, p.value) %>% 
  tk_xts(date_var = date, silent = TRUE)

})



```


```{r message = FALSE,warning = FALSE}
component_contr_matrix_fun <- function(returns, w){
# create covariance matrix
covariance_matrix <- 
  cov(returns)
# calculate portfolio standard deviation
sd_portfolio <- 
  sqrt(t(w) %*% covariance_matrix %*% w)
# calculate marginal contribution of each asset
marginal_contribution <- 
  w %*% covariance_matrix / sd_portfolio[1, 1]
# multiply marginal by weights vecotr
component_contribution <- 
  marginal_contribution * w 
# divide by total standard deviation to get percentages
component_percentages <- 
  component_contribution / sd_portfolio[1, 1] 

component_percentages %>% 
  as_tibble() %>% 
  gather(asset, contribution)
}

interval_sd_by_hand <- 
  function(returns_df, 
           start = 1, 
           window = 24, 
           weights){
  
  # First create start date. 
  start_date <- 
    returns_df$date[start]
  
  # Next an end date that depends on start date and window.
  end_date <-  
    returns_df$date[c(start + window)]
  
  # Filter on start and end date.
  returns_to_use <- 
    returns_df %>% 
    filter(date >= start_date & date < end_date) %>% 
    select(-date)
  
  # Portfolio weights.
  w <- weights

  # Call our original custom function. 
  # We are nesting one function inside another.
  component_percentages <- 
   component_contr_matrix_fun(returns_to_use, w)
  
  # Add back the end date as date column
  results_with_date <- 
    component_percentages %>% 
    mutate(date = ymd(end_date)) %>%
    select(date, everything()) %>% 
    spread(asset, contribution) %>% 
    mutate_if(is.numeric, function(x) x * 100)
}

asset_returns_dplyr_byhand <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  prices <- 
    getSymbols(symbols, src = 'yahoo', from = input$date, 
               auto.assign = TRUE, warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`(symbols)

  
  asset_returns_dplyr_byhand <- 
    prices %>% 
    to.monthly(indexAt = "last", OHLC = FALSE) %>% 
    tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
    gather(asset, returns, -date) %>%
    group_by(asset) %>% 
    mutate(returns = (log(returns) - log(lag(returns)))) %>%
    spread(asset, returns) %>% 
    select(date, symbols) %>% 
    slice(-1)
})

percentages_tibble_pre_built <- eventReactive(input$go, {
  
  asset_returns_xts <- 
    asset_returns_dplyr_byhand() %>% 
    tk_xts(date_col = date)
  
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  portfolio_vol_comp_contr_total_builtin <- 
    StdDev(asset_returns_xts, 
           weights = w,
           portfolio_method = "component")
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  percentages_tibble_pre_built <- 
    portfolio_vol_comp_contr_total_builtin$pct_contrib_StdDev %>%
    tk_tbl(preserve_index = FALSE) %>%
    mutate(asset = symbols) %>%
    rename('risk contribution' = data) %>%
    mutate(`risk contribution` = round(`risk contribution`, 4) * 100, 
           weights = w * 100) %>% 
    select(asset, everything())
  
})


portfolio_vol_components_xts <- eventReactive(input$go, {
  
  asset_returns_dplyr_byhand <- asset_returns_dplyr_byhand()
  
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
portfolio_vol_components_tidy_by_hand <- 
  map_df(1:(nrow(asset_returns_dplyr_byhand) - input$window), 
         interval_sd_by_hand, 
         returns_df = asset_returns_dplyr_byhand, 
         weights = w, 
         window = input$window) %>% 
  tk_xts(date_col = date)
})

portfolio_returns_tq_rebalanced_monthly <- eventReactive(input$go, {
  
  prices <- prices()
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  portfolio_returns_tq_rebalanced_monthly <- 
      prices %>% 
      to.monthly(indexAt = "last", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns)))) %>%
  tq_portfolio(assets_col  = asset, 
               returns_col = returns,
               weights     = w,
               col_rename  = "returns",
               rebalance_on = "months")
})


mean_port_return <- eventReactive(input$go, {
  
  portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  
  mean(portfolio_returns_tq_rebalanced_monthly$returns)
})

stddev_port_return <- eventReactive(input$go, {
  
  portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  
  sd(portfolio_returns_tq_rebalanced_monthly$returns)
})


simulation_accum_1 <- function(init_value, N, mean, stdev) {
    tibble(c(init_value, 1 + rnorm(N, mean, stdev))) %>% 
    `colnames<-`("returns") %>%
    mutate(growth = accumulate(returns, function(x, y) x * y)) %>% 
    select(growth)
}

sims <- eventReactive(input$go, {input$sims})

monte_carlo_sim_51 <- eventReactive(input$go, { 
  
  sims <- sims()
  
  starts <-  
    rep(1, sims) %>%
    set_names(paste("sim", 1:sims, sep = ""))
  
  map_dfc(starts, simulation_accum_1,
          N = input$sim_months, mean = mean_port_return(), 
          stdev = stddev_port_return()) %>% 
  mutate(month = seq(1:nrow(.))) %>% 
  select(month, everything()) %>% 
  `colnames<-`(c("month", names(starts))) %>% 
  gather(sim, growth, -month) %>% 
  group_by(sim) %>% 
  mutate_all(funs(round(., 2)))
  
})
















```
Returns
=====================================================

Row {.tabset .tabset-fade}
-----------------------------------------------------

### Histogram

```{r}
renderPlot({
  portfolio_returns_byhand() %>% ggplot(aes(x=returns)) + geom_histogram(alpha = 0.25,binwidth = 0.01,
                                                                         fill = "cornflowerblue")
})

```

### Density

```{r}
renderPlot({
  portfolio_returns_byhand() %>% 
    ggplot(aes(x=returns)) + 
    geom_density(size = 1,color = "red")
})

```

### Histogram + Density

```{r}
renderPlot({
  portfolio_returns_byhand() %>% 
    ggplot(aes(x=returns)) +
    geom_histogram(alpha = 0.25,binwidth = 0.01,fill = "cornflowerblue") +
    geom_density(geom = "line",size = 1,color = "red")
})


```


Volatility
=========================================

Row {data-height = 500}
----------------------------------------

### rolling vol hc

```{r}
renderHighchart({
  
  port_rolling_sd_xts_hc <- 
    port_rolling_sd_tidy() %>% 
    tk_xts(date_col = date) %>% 
    round(., 4) * 100
  
  highchart(type = "stock") %>% 
    hc_title(text = "Portfolio Rolling Volatility") %>%
    hc_yAxis(title = list(text = "Volatility"),
           labels = list(format = "{value}%"),
           opposite = FALSE) %>% 
    hc_add_series(port_rolling_sd_xts_hc, 
                  name = "Portfolio Vol", 
                  color = "cornflowerblue",
                  id = "Port") %>%
    hc_add_theme(hc_theme_flat()) %>%
    hc_navigator(enabled = FALSE) %>% 
    hc_scrollbar(enabled = FALSE)
})

```


Row {data-height = 500}
------------------------------------------------

### rolling vol ggplot

```{r}
renderPlot({
  port_rolling_sd_tidy() %>% 
    ggplot(aes(x = date)) +
    geom_line(aes(y = rolling_sd), color = "cornflowerblue") + 
    scale_y_continuous(labels = scales::percent) +
    ggtitle("Portfolio Rolling Vol") +
    ylab("volatility") +
    scale_x_date(breaks = pretty_breaks(n = 8)) +
    theme(plot.title = element_text(hjust = 0.5))
})

```


Portfolio Skewness and Kurtosis
==================================================

Row {data-height = 600, .tabset}
--------------------------------------------------

### Rolling Skewness

```{r}
renderHighchart({
  
  highchart(type = "stock") %>%
    hc_title(text = "Rolling Skew") %>%
    hc_add_series(rolling_skew_xts(), name = "rolling skew", color = "cornflowerblue") %>%
    hc_yAxis(title = list(text = "skewness"),
           opposite = FALSE,
           max = 3, 
           min = -3) %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE)  %>% 
    hc_exporting(enabled = TRUE)
})

```

### Rolling Kurtosis

```{r}
renderHighchart({
  
  highchart(type = "stock") %>%
    hc_title(text = "Rolling Kurtosis") %>%
    hc_add_series(rolling_kurt_xts(), 
                  name = "rolling kurt", 
                  color = "cornflowerblue") %>%
    hc_yAxis(title = list(text = "kurtosis"),
           opposite = FALSE,
           max = 3, 
           min = -3) %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) %>% 
  hc_exporting(enabled = TRUE)
})

```


Row {.tabset .tabset-fade}
-----------------------------------

### Histogram 

```{r}
renderPlot({

  portfolio_returns_tq_rebalanced_monthly() %>%
  mutate(hist_col_red = 
           ifelse(returns < (mean(returns) - 2*sd(returns)), 
                  returns, NA),
         hist_col_green = 
           ifelse(returns > (mean(returns) + 2*sd(returns)), 
                  returns, NA),
         hist_col_blue = 
           ifelse(returns > (mean(returns) - 2*sd(returns)) &
                  returns < (mean(returns) + 2*sd(returns)),
                  returns, NA)) %>% 
  ggplot() + 
  
  geom_histogram(aes(x = hist_col_red),
               alpha = .7, 
               binwidth = .003, 
               fill = "red", 
               color = "red") +
  
  geom_histogram(aes(x = hist_col_green),
               alpha = .7, 
               binwidth = .003, 
               fill = "green", 
               color = "green") +
  
  geom_histogram(aes(x = hist_col_blue),
               alpha = .7, 
               binwidth = .003, 
               fill = "cornflowerblue", 
               color = "cornflowerblue") +
  
scale_x_continuous(breaks = pretty_breaks(n = 10)) +
xlab("monthly returns")

})

```

### Density

```{r}
renderPlot({

  portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  mean <- mean(portfolio_returns_tq_rebalanced_monthly$returns)
  median <- median(portfolio_returns_tq_rebalanced_monthly$returns)
  
  skew_density_plot <- portfolio_returns_tq_rebalanced_monthly %>% 
    ggplot(aes(x = returns)) +
    stat_density(geom = "line", size = 1, color = "cornflowerblue")
  
  shaded_area_data <- 
    ggplot_build(skew_density_plot)$data[[1]] %>% 
    filter(x < mean)

  skew_density_plot_shaded <- 
    skew_density_plot + 
    geom_area(data = shaded_area_data, aes(x = x, y = y), fill="pink", alpha = 0.5)
  
  median_line_data <- 
    ggplot_build(skew_density_plot)$data[[1]] %>% 
    filter(x <= median)

skew_density_plot_shaded +
  
  geom_segment(data = median_line_data, aes(x = median, y = 0, xend = median, yend = density), 
               color = "black", linetype = "dotted") +
  
  annotate(geom = "text", x = median, y = 5, label = "median", 
           fontface = "plain", angle = 90, alpha = .8, vjust =  1.75) +
  
  annotate(geom = "text", x = (mean - .03), y = .1, label = "returns < mean", 
           fontface = "plain", color = "red", alpha = .8, vjust =  -1) +
  
  ggtitle("Density Plot Illustrating Skewness")
  

  
})
```

Sharpe Ratio
==============================================

Row {data-height=800}
----------------------------------------------

### Rolling Sharpe

```{r}
renderHighchart({
  
  validate(need(input$go, "Please choose your portfolio assets, weights, rfr, rolling window and start date and click submit."))
  
  
  highchart(type = "stock") %>%
  hc_title(text = "Rolling Sharpe") %>%
  hc_add_series(portfolio_rolling_sharpe(), name = "Portfolio", color = "cornflowerblue") %>%
  hc_add_series(market_rolling_sharpe(), name = "Market", color = "green") %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) %>% 
  hc_exporting(enabled = TRUE) %>% 
  hc_legend(enabled = TRUE, align = "right", verticalAlign = "middle",
            layout = "vertical")

  
})
```

Row {data-height=200}
-----------------------------------------------------------------------

### The Sharpe Ratio of Your Portfolio

```{r}
renderValueBox({
  
  
  valueBox(value = tags$p(round(portfolio_sharpe(), 4), 
                          style = "font-size: 70%;"), 
           color = "primary")
})

```

### Sharpe Ratio of S&P500 in same time period

```{r}
renderValueBox({
  
  valueBox(value = tags$p(round(market_sharpe(), 4), 
                          style = "font-size: 70%;"), 
           color = "primary")
})

```

CAPM
===================================================

Row {data-height=650}
---------------------------------------------------

### CAPM Highcharter

```{r}
renderHighchart({

portfolio_model_augmented <- portfolio_model_augmented()

highchart() %>% 
  hc_title(text = "Scatter with Regression Line") %>% 
  hc_add_series(portfolio_model_augmented, 
                type = "scatter",
                color = "cornflowerblue",
                hcaes(x = round(mkt_rtns, 4), 
                      y = round(returns, 4),
                      date = date), 
                name = "Returns") %>%
  hc_add_series(portfolio_model_augmented, 
                type = "line", 
                enableMouseTracking = FALSE,
                hcaes(x = mkt_rtns, y = .fitted), 
                name = "CAPM Beta = Slope of Line") %>% 
  hc_xAxis(title = list(text = "Market Returns")) %>% 
  hc_yAxis(title = list(text = "Portfolio Returns")) %>% 
  hc_tooltip(formatter = JS("function(){
     return ('port return: ' + this.y + '  mkt return: ' + this.x +  
     '  date: ' + this.point.date)}"))%>% 
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE)


})
```

Row 2 {data-height=350}
---------------------------------------

### Model Results

```{r}
renderTable({
  beta_dplyr_byhand() %>% 
  tidy(model) %>% 
  mutate(term = c("alpha", "beta"))
}, digits = 4)
```


Fama French 
========================================

Row 1
----------------------------------------

### Rolling r squared

```{r}
renderHighchart({
  
 rolling_ff_glanced <- rolling_ff_glanced()
  
  highchart(type = "stock") %>% 
  hc_add_series(rolling_ff_glanced$adj.r.squared,
                color = "cornflowerblue",
                name = "r-squared") %>% 
  hc_title(text = "Rolling FF 3-Factor R-Squared") %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) %>% 
  hc_exporting(enabled = TRUE)
})
```


Row 2 {.tabset}
-------------------

### Model Results

```{r}
renderTable({
  ff_dplyr_byhand()
})
```

### Betas

```{r}
renderPlot({
  ff_dplyr_byhand() %>%
  ggplot(aes(x = term, 
             y = estimate, 
             shape = term, 
             color = term)) + 
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(title = "FF 3-Factor Coefficients",
       subtitle = "with conf intervals",
       x = "",
       y = "coefficient",
       caption = "data source: FF website and yahoo! Fin") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption  = element_text(hjust = 0))

    })
```
  


Volatility
========================

Row 1 {.tabset}
-----------------------------------------

### Asset Contribution Highcharter

```{r}
renderHighchart({

  portfolio_vol_components <- 
    portfolio_vol_components_xts()
  
  highchart(type = "stock") %>% 
    hc_title(text = "Volatility Contribution") %>%
    hc_add_series(portfolio_vol_components[, 1], 
                  name = names(portfolio_vol_components[, 1])) %>%
    hc_add_series(portfolio_vol_components[, 2], 
                  name = names(portfolio_vol_components[, 2])) %>%
    hc_add_series(portfolio_vol_components[, 3], 
                  name = names(portfolio_vol_components[, 3])) %>%
    hc_add_series(portfolio_vol_components[, 4], 
                  name = names(portfolio_vol_components[, 4])) %>% 
    hc_add_series(portfolio_vol_components[, 5], 
                  name = names(portfolio_vol_components[, 5])) %>% 
    hc_add_theme(hc_theme_flat()) %>% 
    hc_yAxis(
      labels = list(format = "{value}%"), 
             opposite = FALSE, 
             min = min(portfolio_vol_components) -5,
             max = max(portfolio_vol_components) + 5) %>%
    hc_navigator(enabled = FALSE) %>% 
    hc_scrollbar(enabled = FALSE)
})
```

### Stacked Area Chart

```{r}
renderHighchart({
  portfolio_vol_components <- 
    portfolio_vol_components_xts()
  
 highchart() %>% 
  hc_chart(type = "area") %>% 
  hc_title(text = "Stacked Volatility Contribution") %>%
  hc_plotOptions(area = list(
     stacking = "percent",
     lineColor = "#ffffff",
     lineWidth = 1,
     marker = list(
       lineWidth = 1,
       lineColor = "#ffffff"
       ))
     ) %>% 
    hc_add_series(portfolio_vol_components[, 1], 
                  name = names(portfolio_vol_components[, 1])) %>%
    hc_add_series(portfolio_vol_components[, 2], 
                  name = names(portfolio_vol_components[, 2])) %>%
    hc_add_series(portfolio_vol_components[, 3], 
                  name = names(portfolio_vol_components[, 3])) %>%
    hc_add_series(portfolio_vol_components[, 4], 
                  name = names(portfolio_vol_components[, 4])) %>% 
    hc_add_series(portfolio_vol_components[, 5], 
                  name = names(portfolio_vol_components[, 5])) %>% 
     hc_yAxis(labels = list(format = "{value}%"),
      opposite = FALSE) %>%
  hc_xAxis(type = "datetime") %>%
  hc_tooltip(pointFormat = 
"
{series.name}:{point.percentage:.1f}%",
             shared = TRUE) %>% 
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) %>% 
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE) %>% 
  hc_legend(enabled = TRUE)
})
```



Row
------------------------


### bar chart with weights

```{r}
renderPlot(
  percentages_tibble_pre_built() %>% 
  gather(type, percent, -asset) %>% 
  group_by(type) %>% 
  mutate(percent = percent/100) %>% 
  ggplot(aes(x = asset, y = percent, fill = type)) +
  geom_col(position = 'dodge') + 
  scale_y_continuous(labels = percent) + 
  ggtitle("Percent Contribution to Volatility") +
  theme(plot.title = element_text(hjust = 0.5))
)
```


Simulated Growth
=====================================  

Row {data-height=600, .tabset}
-----------------------------------------------------------------------

### Sim Vis highcharter

```{r}
renderHighchart(
  hchart( monte_carlo_sim_51(), 
       type = 'line', 
       hcaes(y = growth,
             x = month,
             group = sim)) %>% 
  hc_title(text = paste(sims(), "Simulations", sep = " ")) %>%
  hc_xAxis(title = list(text = "months")) %>%
  hc_yAxis(title = list(text = "dollar growth"),
           labels = list(format = "${value}")) %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE) %>% 
  hc_legend(enabled = FALSE)
)
```


Row
-------------------------------------

### Min, Max, Median Sim

```{r}
renderHighchart({
 
sim_summary <- 
  monte_carlo_sim_51() %>%
  summarise(final = last(growth)) %>% 
  summarise(
            max = max(final), 
            min = min(final),
            median = median(final))

mc_max_med_min <- 
  monte_carlo_sim_51() %>%
  filter(
      last(growth) == sim_summary$max || 
      last(growth) == sim_summary$median ||
      last(growth) == sim_summary$min)

  hchart(mc_max_med_min, 
       type = 'line', 
       hcaes(y = growth,
             x = month,
             group = sim)) %>% 
  hc_title(text = "Min Max Median Simulations") %>%
  hc_xAxis(title = list(text = "months")) %>%
  hc_yAxis(title = list(text = "dollar growth"),
           labels = list(format = "${value}")) %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE) %>% 
  hc_legend(enabled = FALSE)
})
```

